sudo: required
language: ruby
services:
- docker
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker pull nimbl3/athena-web:chore_gitlab-ci
- docker images
- docker run nimbl3/athena-web:chore_gitlab-ci
- docker run test yarn lint
- docker run test rspec --exclude-pattern "spec/systems/**/*_spec.rb"
  --profile
- docker run test rspec spec/systems/ --profile